<?php
if( !isset($OWEXEC) )
    die("You don't have permissions to access this file");

$countries = array(
   "Afghanistan", 
   "&Auml;gypten",
   "Afghanistan",
   "&Auml;gypten",
   "Aland",
   "Albanien",
   "Algerien",
   "Amerikanisch-Samoa",
   "Amerikanische Jungferninseln",
   "Andorra",
   "Angola",
   "Anguilla",
   "Antarktis",
   "Antigua und Barbuda",
   "&Auml;quatorialguinea",
   "Argentinien",
   "Armenien",
   "Aruba",
   "Ascension",
   "Aserbaidschan",
   "&Auml;thiopien",
   "Australien",
   "Bahamas",
   "Bahrain",
   "Bangladesch",
   "Barbados",
   "Belgien",
   "Belize" ,
   "Benin" ,
   "Bermuda" ,
   "Bhutan" ,
   "Bolivien" ,
   "Bosnien und Herzegowina",
   "Botswana",
   "Bouvetinsel",
   "Brasilien",
   "Brunei",
   "Bulgarien",
   "Burkina Faso",
   "Burundi",
   "Chile",
   "China",
   "Cookinseln",
   "Costa Rica",
   "Cote d'Ivoire",
   "D&auml;nemark",
   "Deutschland",
   "Diego Garcia",
   "Dominica",
   "Dominikanische Republik",
   "Dschibuti",
   "Ecuador",
   "El Salvador",
   "Eritrea",
   "Estland",
   "Europ&auml;ische Union",
   "Falklandinseln",
   "F&auml;r&ouml;er",
   "Fidschi",
   "Finnland",
   "Frankreich",
   "Franz&ouml;sisch-Guayana",
   "Franz&ouml;sisch-Polynesien",
   "Gabun",
   "Gambia" ,
   "Georgien",
   "Ghana",
   "Gibraltar",
   "Grenada",
   "Griechenland",
   "Gr&ouml;nland",
   "Gro&szlig;britannien",
   "Guadeloupe",
   "Guam",
   "Guatemala",
   "Guernsey" ,
   "Guinea" ,
   "Guinea-Bissau" ,
   "Guyana" ,
   "Haiti",
   "Heard und McDonaldinseln" ,
   "Honduras" ,
   "Hongkong" ,
   "Indien" ,
   "Indonesien" ,
   "Irak" ,
   "Iran" ,
   "Irland" ,
   "Island",
   "Israel",
   "Italien" ,
   "Jamaika" ,
   "Japan",
   "Jemen" ,
   "Jersey" ,
   "Jordanien" ,
   "Kaimaninseln" ,
   "Kambodscha" ,
   "Kamerun" ,
   "Kanada" ,
   "Kanarische Inseln" ,
   "Kap Verde" ,
   "Kasachstan" ,
   "Katar" ,
   "Kenia" ,
   "Kirgisistan" ,
   "Kiribati" ,
   "Kokosinseln" ,
   "Kolumbien" ,
   "Komoren" ,
   "Kongo" ,
   "Kroatien" ,
   "Kuba" ,
   "Kuwait" ,
   "Laos" ,
   "Lesotho" ,
   "Lettland" ,
   "Libanon" ,
   "Liberia" ,
   "Libyen" ,
   "Liechtenstein" ,
   "Litauen" ,
   "Luxemburg" ,
   "Macao" ,
   "Madagaskar" ,
   "Malawi" ,
   "Malaysia" ,
   "Malediven",
   "Mali",
   "Malta" ,
   "Marokko" ,
   "Marshallinseln" ,
   "Martinique" ,
   "Mauretanien" ,
   "Mauritius",
   "Mayotte",
   "Mazedonien" ,
   "Mexiko" ,
   "Mikronesien" ,
   "Moldawien" ,
   "Monaco" ,
   "Mongolei" ,
   "Montserrat" ,
   "Mosambik" ,
   "Myanmar" ,
   "Namibia" ,
   "Nauru" ,
   "Nepal" ,
   "Neukaledonien" ,
   "Neuseeland" ,
   "Neutrale Zone"  ,
   "Nicaragua" ,
   "Niederlande" ,
   "Niederl&auml;ndische Antillen",
   "Niger" ,
   "Nigeria" ,
   "Niue" ,
   "Nordkorea" ,
   "N&ouml;rdliche Marianen",
   "Norfolkinsel" ,
   "Norwegen" ,
   "Oman" ,
   "&Ouml;sterreich" ,
   "Pakistan" ,
   "Pal&auml;stina" ,
   "Palau" ,
   "Panama" ,
   "Papua-Neuguinea" ,
   "Paraguay" ,
   "Peru" ,
   "Philippinen" ,
   "Pitcairninseln", 
   "Polen" ,
   "Portugal", 
   "Puerto Rico",
   "R&eacute;union",
   "Ruanda" ,
   "Rum&auml;nien",
   "Russische F&ouml;deration",
   "Salomonen" ,
   "Sambia" ,
   "Samoa" ,
   "San Marino", 
   "S&acirc;o Tom&eacute; und Pr&iacute;ncipe",
   "Saudi-Arabien",
   "Schweden" ,
   "Schweiz" ,
   "Senegal" ,
   "Serbien und Montenegro",
   "Seychellen" ,
   "Sierra Leone",
   "Simbabwe" ,
   "Singapur" ,
   "Slowakei" ,
   "Slowenien" ,
   "Somalia" ,
   "Spanien" ,
   "Sri Lanka",
   "St. Helena",
   "St. Kitts und Nevis",
   "St. Lucia",
   "St. Pierre und Miquelon",
   "St. Vincent/Grenadinen (GB)",
   "S&uuml;dafrika, Republik",
   "Sudan",
   "S&uuml;dkorea",
   "Suriname",
   "Svalbard und Jan Mayen",
   "Swasiland",
   "Syrien",
   "Tadschikistan",
   "Taiwan",
   "Tansania",
   "Thailand",
   "Timor-Leste",
   "Togo" ,
   "Tokelau" ,
   "Tonga" ,
   "Trinidad und Tobago",
   "Tristan da Cunha",
   "Tschad",
   "Tschechische Republik",
   "Tunesien",
   "T&uuml;rkei" ,
   "Turkmenistan" ,
   "Turks- und Caicosinseln",
   "Tuvalu" ,
   "Uganda" ,
   "Ukraine" ,
   "Ungarn" ,
   "Uruguay" ,
   "Usbekistan" ,
   "Vanuatu" ,
   "Vatikanstadt" ,
   "Venezuela",
   "Vereinigte Arabische Emirate",
   "Vereinigte Staaten von Amerika",
   "Vietnam",
   "Wallis und Futuna",
   "Weihnachtsinsel",
   "Wei&szlig;russland",
   "Westsahara",
   "Zentralafrikanische Republik",
   "Zypern");
   
   if(!isset($selectedCountry))
   		$selectedCountry = "&Ouml;sterreich";
   
   for($i = 0; $i < sizeof($countries); $i++)
   {
   		echo "<option value=" . $countries[$i] . " ";
   		if(isset($selectedCountry))
   		{
   			if($selectedCountry == $countries[$i])
   				echo "selected=\"selected\"";
   		}
		echo ">" . $countries[$i]. "</option>";
   }
